### ISSUE TITLE
本地预览可以，但是线上预览就不显示，怎么解决？

### ISSUE THREAD

**Issue by jarvislin94** [bubkoo/hexo-filter-flowchart#2]

**Comment by bubkoo** [comment]
@JackZong 确保 flowchart 的资源都加载成功了吗

**Comment by jarvislin94** [comment]
只需要在站点_config.yml文件中配置吗？
flowchart:
  raphael:
  flowchart:
  options: # options used for `drawSVG`
本地每次hexo-g后好像要修改下那个```flow 才会正常显示，然后线上的直接不显示，不管怎么上传@bubkoo

**Comment by babopo** [comment]
同样的问题。。

**Comment by bubkoo** [comment]
@JackZong @babopo 
配置中
```
flowchart:
    # raphael:     # 这是 raphael.js 资源的地址，一般使用系统默认，不需要配置
    # flowchart:   # 这是 flowchart.js 资源的地址，一般使用系统默认，不需要配置
```

这两项配置需要注释掉，或者直接删掉

**Comment by jarvislin94** [comment]
@bubkoo 还是不行

**Comment by bubkoo** [comment]
@JackZong 你线上的地址发我 我访问以下试试

**Comment by jarvislin94** [comment]
@bubkoo http://jackzong.github.io/2017/04/13/2017-04-13-shift+f2/

**Comment by bubkoo** [comment]
@JackZong 还是没看出来问题，你都安装了哪些插件，要不先禁用一些插件试试

**Comment by Potat0000** [comment]
我也遇到了同样的问题。好像是```renderer.js```中的```before```部分被正常执行，而```after```部分似乎没有执行，所以只被插入了```<div id="flowchart-0" class="flow-chart"></div>```

本地预览时出现这个问题可以把```flow中的一个或几个字母删除后重新添加（只要不是flow就可以），但发布时就没有办法了

**Comment by Potat0000** [comment]
@bubkoo 似乎```flows.length```在```after```中的返回值始终为0，导致```after```的判断总是不通过

**Comment by bubkoo** [comment]
@gyj1109 已经 merge
@JackZong @babopo 使用 v1.0.3
